# Your GitHub Actions workflow
name: Sync Repositories

on: [push] 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: 'davidfortytwo/rivm-screenit'
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
          path: src_repo

      - name: Checkout Destination Repo
        uses: actions/checkout@v2
        with:
          repository: 'davidfortytwo/rivm-screenit'
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
          path: dest_repo

      - name: Sync Repositories
        run: |
          rsync -a --delete src_repo/ dest_repo/
          cd dest_repo
          git config user.name 'davidfortytwo'
          git config user.email 'null'
          git add .
          git commit -m "Sync with source repo"
          git push
